# GRID
TOTAL_BLOCKS_Y = 18
TOTAL_BLOCKS_X = 10
SPAWN_X = 3
BORDER_WIDTH = 1

# DISPLAY
LINE_COLOR = (66, 134, 244)

# GAME
GAME_NAME = "TETRIS"
STARTING_DROP_RATE = 200

# DEVELOPER
TEST_ROTATE_MODE = True
TEST_ROTATE_MODE_SHAPE = 1